### ISSUE TITLE
Match fonts across site

### ISSUE THREAD

**Issue by Lazytangent** [Lazytangent/TheJuiceBox#80]
All sans-serif for consistency

**Comment by kamekazz** [comment]
I'll do most of the UI work, but I really don't want to set up an environment database.
Is there any way you can help? I am not used to using PostgreSQL.

**Comment by Lazytangent** [comment]
Hey @kamekazz! I really appreciate you reaching out to help with the project, but currently, I can't quite accept yet since this is meant to be a solo project done as part of a bootcamp's curriculum. That said, I really do appreciate you reaching out.

As for the PostgreSQL, if you're on MacOS, you can install it with Homebrew: https://wiki.postgresql.org/wiki/Homebrew or if you're on Windows, I've been told that WSL would work if you have that set up: https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database

Let me know if I can help out any more than that with the PostgreSQL set up, I'd be more than happy to help out.

**Comment by kamekazz** [comment]
@Lazytangent ❤️
